### ISSUE TITLE
Security concern about private key terms in public context

### ISSUE THREAD

**Issue by clehner** [decentralized-identity/EcdsaSecp256k1RecoverySignature2020#15]
@msporny [wrote](https://github.com/perma-id/w3id.org/pull/2108#issuecomment-818392336):

> You will also want to avoid providing terms to express private key values in public contexts... private key values shouldn't escape your systems. It's an anti-pattern for a public vocabulary (that doesn't come with lots of warnings).

This suite's context file currently defines terms for private key values - `privateKeyJwk` and `privateKeyHex`. Also, they are defined not in the w3id security namespace, so could potentially conflict with other uses (#14).

**Comment by OR13** [comment]
@clehner feel free to ignore the head in the sand approach of not defining terms for private keys... JSON-LD is a semantic technology not a schema, and should not be used in isolation to prevent private key disclosure.... 

Your software should ensure that, don't trust JSON-LD to do it for you.... defining the data model you are using fully is the opposite of an anti pattern, its what developers expect.

In fact, we have a data model for private data here:

https://github.com/w3c-ccg/universal-wallet-interop-spec

Where we express private keys, but also, mnemonics, and other sensitive information in JSON-LD... I can't disagree with manu more on this issue...
